### ISSUE TITLE
Server crash when user tries to log in

### ISSUE THREAD

**Issue by DancinWhale** [Cursee-Development/Sleepy-Hollows#3]
### Mod Version

1.0.1

### Latest Version

- [X] Yes, I’m using the latest version.

### Issue Description

I install the mod on the server and the client. When starting both the server and the client everything is fine, but when trying to log in the server crashes.

### Steps to Reproduce

1. Install the mod on the server
2. Install the mod on the client
3. Log in to the server

### Logs

[11:22:43 ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/client/player/LocalPlayer
        at net.satisfy.sleepy_hollows.SleepyHollows.onServerTick(SleepyHollows.java:48) ~[_CONT%20Sleepy%20Hollows%20v1.0.1.jar%23455!/:?]
        at net.satisfy.sleepy_hollows.forge.SleepyHollowsForge$SleepyHollowsEventHandlers.onServerTick(SleepyHollowsForge.java:48) ~[_CONT%20Sleepy%20Hollows%20v1.0.1.jar%23455!/:?]
        at net.satisfy.sleepy_hollows.forge.__SleepyHollowsEventHandlers_onServerTick_ServerTickEvent.invoke(.dynamic) ~[_CONT%20Sleepy%20Hollows%20v1.0.1.jar%23455!/:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactory.java:974) ~[forge-1.20.1-47.3.5-universal.jar%23575!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1068) ~[server-1.20.1-20230612.114412-srg.jar%23570!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:909) ~[server-1.20.1-20230612.114412-srg.jar%23570!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285) ~[server-1.20.1-20230612.114412-srg.jar%23570!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.player.LocalPlayer
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:157) ~[securejarhandler-mohist-2.1.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 11 more

### Minimal Instance Test

- [ ] Yes, I’ve tested it with a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by McPersson** [comment]
Yeah, same thing. When I analyzed it, I got this: 

> The issue in this crash is caused by an attempt to load the client class LocalPlayer on the server, which is not allowed because the server does not support client-side classes. The error is triggered by the Sleepy Hollows mod, which is attempting to call a client-only class in a server environment. This is a common issue of incompatibility between client and server components of mods.

On the client everything is fine, when you go to the server - the server crashes.

**Comment by McPersson** [comment]
At the same time, if you remove the modification, **your world is doomed**. It says that the element ResourceKey[minecraft
/noise / sleepy_hollows] is missing, causing an IllegalStateException error. This is the first time I’ve encountered something like this.

Under no circumstances should you install this mod on your server.

**Comment by satisfyu** [comment]
@jason13official fixed this. I'll upload the fixed version later today. :)

**Comment by satisfyu** [comment]
Fixed in 1.0.2. 

https://legacy.curseforge.com/minecraft/mc-mods/sleepy-hollows/files/all

**Comment by Kurefu** [comment]
Created an account to expand on this... 

I downloaded the latest--specifically 1.0.2 forge--onto our existing modded server. Everything seems fine until I tried to load some chunks that should've had the sleepy-hollow's biome, and every time we get close the server freezes completely, crashing a minute or so later. 

I've restart the server successfully around 7 times--it still crashes when loading said chunks--and upon removing the mod, the server won't boot up entirely...

EDIT: So, turns out it was a different mod that was crashing upon loading it's chunks, however when I removed the Sleepy Hollows mod, it completely bricked the server either way
